name: 'ecommerce_dbt'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dbt:

    bronze:
      +materialized: view
      +schema: "{{ env_var('DBT_BRONZE_SCHEMA') }}"

    silver:
      +materialized: view
      +schema: "{{ env_var('DBT_SILVER_SCHEMA') }}"

    gold:
      +materialized: table
      +schema: "{{ env_var('DBT_GOLD_SCHEMA') }}"
      
      fact_order_items:
        +materialized: incremental